# Site settings
title: Digital Rain C++ Project Blog
author:
  name: Mark Veerasingam
  email: G00403931@atu.ie
description: ""

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme